language: objective-c

branches:
  only:
    - master

xcode_project: Buttton.xcodeproj
xcode_scheme: ButttonTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild test -project Buttton.xcodeproj -scheme ButttonTests -destination "platform=iOS Simulator,name=iPhone 6s"
